name: Echo-auto-deploy

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "1 2 * * *"
    - cron: "3 4 * * *"
    - cron: "5 6 * * *"
    - cron: "7 8 * * *"
    - cron: "9 10 * * *"
    - cron: "11 12 * * *"
    - cron: "13 14 * * *"
    - cron: "15 16 * * *"
    - cron: "17 18 * * *"
    - cron: "19 20 * * *"
    - cron: "21 22 * * *"
    - cron: "23 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "s0912758806p@gmail.com"
          git config --local user.name "Gorman"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MYSELF_PAT_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
